<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Voting\CPanel\Doctrine;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

<div class="row">
    <div class="col-md-12">

        <?php if (!$this->paginator->count()) : ?>

            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no vote option, click "Create new vote option" to start working with the vote option.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                        <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new poll option'); ?></a>
                    <?php endif; ?>
                </p>
            </div>

        <?php else: ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">
                            <?= $this->form()->openTag((new \Zend\Form\Form)->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>
                            <div class="form-group has-feedback">
                                <?= $this->formSearch(
                                    (new \Zend\Form\Element\Search('q'))->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => $this->translate('Search...')
                                    ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                                <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                                   class="btn btn-success"><?= $this->translate('Create new poll option'); ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th><?= $this->translate('Name'); ?></th>
                            <th><?= $this->translate('Poll'); ?></th>
                            <th><?= $this->translate('Ponderability'); ?></th>
                            <th><?= $this->translate('Priority'); ?></th>
                            <th><?= $this->translate('Created At'); ?></th>
                            <th><?= $this->translate('Modified At'); ?></th>
                            <th width="100px" class="text-center">
                                <?= $this->translate('Actions'); ?>
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php /** @var \MSBios\Voting\Resource\Doctrine\Entity\Option $item */ ?>
                        <?php foreach ($this->paginator as $item): ?>
                            <tr>
                                <td><?= $this->escapeHtml($item->getName()); ?></td>
                                <td><?= $this->escapeHtml($item->getPoll()->getSubject()); ?></td>
                                <td><?= $this->escapeHtml($item->getPonderability()); ?></td>
                                <td><?= $this->escapeHtml($item->getPriority()); ?></td>
                                <td>
                                    <?= $this->dateFormat(
                                        $item->getCreatedAt(),
                                        \IntlDateFormatter::MEDIUM,
                                        \IntlDateFormatter::SHORT);
                                    ?>
                                </td>
                                <td>
                                    <?= $this->dateFormat(
                                        $item->getModifiedAt(),
                                        \IntlDateFormatter::MEDIUM,
                                        \IntlDateFormatter::SHORT);
                                    ?>
                                </td>
                                <td class="text-center">

                                    <?= $this->partial('partial/actions.phtml', [
                                        'matchedRouteName' => $this->matchedRouteName,
                                        'identifier' => $item->getId()
                                    ]); ?>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                        'route' => $this->matchedRouteName
                    ]); ?>

                </div>

            </div>
        <?php endif; ?>

    </div> <!-- end col -->
</div>
