<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Voting\CPanel\Doctrine;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

<div class="row">
    <div class="col-md-12">

        <?php if (!$this->paginator->count()) : ?>

            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no vote option, click "Create new vote option" to start working with the vote option.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->config->get('resource'), 'add')): ?>
                        <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new vote option'); ?></a>
                    <?php endif; ?>
                </p>
            </div>

        <?php else: ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">
                            <?= $this->form()->openTag((new \Zend\Form\Form)->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>
                            <div class="form-group has-feedback">
                                <?= $this->formSearch(
                                    (new \Zend\Form\Element\Search('q'))->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => $this->translate('Search...')
                                    ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <?php if ($this->isAllowed($this->config->get('resource'), 'add')): ?>
                                <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'add']); ?>"
                                   class="btn btn-success"><?= $this->translate('Create new person'); ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th><?= $this->translate('Name'); ?></th>
                            <th><?= $this->translate('Poll'); ?></th>
                            <th><?= $this->translate('Total'); ?></th>
                            <th><?= $this->translate('Created At'); ?></th>
                            <th><?= $this->translate('Modified At'); ?></th>
                            <th width="1px" class="text-center">
                                <?= $this->translate('Actions'); ?>
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php /** @var \MSBios\Voting\Resource\Doctrine\Entity\Option $item */ ?>
                        <?php foreach ($this->paginator as $item): ?>
                            <tr>
                                <td><?= $this->escapeHtml($item->getName()); ?></td>
                                <td><?= $this->escapeHtml($item->getPoll()->getSubject()); ?></td>
                                <td><?= $this->escapeHtml($item->getTotal()); ?></td>
                                <td>
                                    <?= $this->dateFormat(
                                        $item->getCreatedAt(),
                                        \IntlDateFormatter::MEDIUM,
                                        \IntlDateFormatter::SHORT);
                                    ?>
                                </td>
                                <td>
                                    <?= $this->dateFormat(
                                        $item->getModifiedAt(),
                                        \IntlDateFormatter::MEDIUM,
                                        \IntlDateFormatter::SHORT);
                                    ?>
                                </td>
                                <td class="text-center">

                                    <?php /** @var string $identifierTrashModal */ ?>
                                    <?php $identifierTrashModal = "modal-confirm-{$item->getId()}"; ?>

                                    <ul class="icons-list">

                                        <?php if ($this->isAllowed($this->config->get('resource'), 'edit')): ?>
                                            <li>
                                                <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'edit', 'id' => $item->getId()]); ?>">
                                                    <i class="icon-pencil"></i>
                                                </a>
                                            </li>
                                        <?php endif; ?>

                                        <?php if ($this->isAllowed($this->config->get('resource'), 'drop')): ?>
                                            <li class="text-danger-600">
                                                <a href="#"
                                                   data-toggle="modal"
                                                   data-target="#<?= $identifierTrashModal; ?>">
                                                    <i class="icon-trash"></i>
                                                </a>
                                            </li>
                                        <?php endif; ?>

                                    </ul>

                                    <!-- Modal -->
                                    <div class="modal fade"
                                         id="<?= $identifierTrashModal; ?>"
                                         tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Are you sure?</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Do you want to delete the entry?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button"
                                                            class="btn btn-default"
                                                            data-dismiss="modal">
                                                        Cancel
                                                    </button>
                                                    <a href="<?= $this->url($this->config->get('route_name'), [
                                                        'action' => 'drop',
                                                        'id' => $item->getId()
                                                    ]); ?>" class="btn btn-primary">
                                                        Yes, delete it!
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                        'route' => $this->config->get('route_name')
                    ]); ?>

                </div>

            </div>
        <?php endif; ?>

    </div> <!-- end col -->
</div>
